name: Fast Webhook Trigger (30s Loop)

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:       # Allow manual runs

jobs:
  rapid-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Loop and Trigger Every 30s
        run: |
          for i in {1..10}; do
            curl -X POST \
              -H "Content-Type: application/json" \
              -H "X-GitHub-Event: rapid-ping" \
              -d '{"interval": "30s"}' \
              https://pcms.epizy.com/portal/webhooktest.php
            sleep 30  # Wait 30 seconds
          done
