name: Daily 7 AM Webhook Trigger

on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7:00 AM UTC every day
  workflow_dispatch:     # (Optional) Allows manual triggering

jobs:
  call-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: scheduled" \
            -H "X-Hub-Signature-256: sha256=$(echo -n '{"time":"7am"}' | openssl dgst -sha256 -hmac "${{ secrets.WEBHOOK_SECRET }}" | awk '{print $2}')" \
            -d '{"time": "7am"}' \
            https://pcms.epizy.com/portal/required/birthday_students.php
